// <auto-generated />
namespace App.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcreateddatepropertytouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcreateddatepropertytouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201603301911118_add-created-date-property-to-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
