// <auto-generated />
namespace App.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intialsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intialsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201603301908346_intial-setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
